### ISSUE TITLE
Translate the pseudo-code below into C++ code

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW4#1]
I'll be working on:

- Translate the pseudo-code below into C++ code (1 member due till Wednesday 2pm) that will be wrapped in a python function with docstrings and unit tests (1 member due till HW deadline)

**Comment by dnxjay** [comment]
ill translate the pseudo-code into python code

**Comment by SchrodingersStruggle** [comment]
I would like to work on generating the least square fit.

**Comment by laserlab** [comment]
> I would like to work on generating the least square fit.

you can work together with @dnxjay on it. I think there was only one for this task in class. Can you both then make a new issue with a descriptive title and assigne the respective milestone to it?

**Comment by iglesias-cardinale** [comment]
I'll work on 

- Select the 9 groups (open circles) in Figure 1 of [Hubble's 1929 article](https://www.pnas.org/content/pnas/15/3/168.full.pdf)(due till Monday 2pm)(1 member)

**Comment by laserlab** [comment]
Do you want to talk about your reasoning to use cython today in class quick?
