### ISSUE TITLE
Confusion on task I've been assigned

### ISSUE THREAD

**Issue by SchrodingersStruggle** [ubsuny/CP1-24-HW4#15]
@laserlab I am a bit confused on my task, as in #1 I volunteered to make the least square fit for the csv someone produces when that's completed, but it seems like I was assigned to translate the pseudo code instead. Is there any way I could get some clarification on this?

**Comment by SchrodingersStruggle** [comment]
To follow up, if it was the original intention to have me working on the unit testing for the pseudo python code, I wouldn't mind that. Especially if the least square fitting step is just generating a figure, as originally I thought it was going to be making a least square fitting function.

**Comment by laserlab** [comment]
Sorry I thought that’s what you meant with generating the least square fit, so you you want to do #9 ?

**Comment by laserlab** [comment]
assigned #9
