### ISSUE TITLE
Should we add a libraries.txt file ?

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW4#18]
I'm thinking of adding a file listing all the libraries that everyone is going to use for it to be easier for the workflows files to install those dependencies, and in turn I'm thinking of opening a new issue for all to list the "different" libraries they're going to use. Or is it not necessary

**Comment by laserlab** [comment]
See #17. Please use a `requirements.txt` that can be used in github actions and in the code space.

**Comment by laserlab** [comment]
See: https://pip.pypa.io/en/stable/reference/requirements-file-format/
