### ISSUE TITLE
Translate the pseudo-code into python code 

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW4#2]
I will be responsible for translating the pseudo-code below into python code

**Comment by dnxjay** [comment]
Any questions about this can be done here since its a task that has to be done early

**Comment by laserlab** [comment]
see #1

**Comment by laserlab** [comment]
see #9

**Comment by laserlab** [comment]
~assigned documentation and unit testing part to~ @haiderabbas007

**Comment by laserlab** [comment]
reassigned @SchrodingersStruggle to this see discussion in #13

**Comment by dnxjay** [comment]
@laserlab so who's now responsible for documentation and unit testing?

**Comment by SchrodingersStruggle** [comment]
@dnxjay 
After some discussion, I am now responsible for that. I will begin reviewing your PR immediately and will have that sorted very soon.

**Comment by avgagliardo** [comment]
I just pushed the Cython version of the code in PR #17

**Comment by dnxjay** [comment]
well done guys keeping on schedule with the tasks

**Comment by dnxjay** [comment]
closing now.
