### ISSUE TITLE
Milestone goal.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW4#20]
We need 6 more milestones to meet the goal. Feel free to discuss some ideas here.

**Comment by avgagliardo** [comment]
Maybe a milestone for general unit testing, although that might already be covered by certain task descriptions.

**Comment by laserlab** [comment]
I was a little cheap on milestones for the tasks. I’m also happy to change it to 12 with the same amount of points. Let me know

**Comment by kylemasc917** [comment]
If we can't make it to 18 by class tomorrow maybe it would be a good idea to lower the requirements.

**Comment by jkblc** [comment]
The number of milestones has been changed with PR #45
