### ISSUE TITLE
Requirements.txt and Package Dependencies

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW4#23]
~~PR #22~~ PR  #21 adds a requirements.txt file to the root project directory. If anyone is using a python package that hasn't been included, feel free to add it in.

Also, here is a brief tutorial on [how to make and use requirements.txt](https://learnpython.com/blog/python-requirements-file/).

**Comment by HeshamElsaman** [comment]
For future notices, please see #21
Apologies for any inconvenience.

**Comment by avgagliardo** [comment]
> For future notices, please see #21 Apologies for any inconvenience.

thank you for the correction. I just updated the main post.

**Comment by avgagliardo** [comment]
closing this issue
