### ISSUE TITLE
Uncertainties in raw data

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW4#26]
I am doing the task:

- Make a least-squares fit **with uncertainties** to the 9 groups using the code above). 

I do have the x and y data which are the distances and velocities respectively. I need to include the uncertainties as well as is indicated above. 

Two questions: 

1) Do I only need uncertainties in y, or in x as well?

2) To calculate these uncertainties, do I use half of the range?

**Comment by laserlab** [comment]
If you add appropriate milestone and mention the person for that task there is a higher chance for getting a response

**Comment by haiderabbas007** [comment]
Ok, I figured these, thanks
