### ISSUE TITLE
Why no uncertainties in x?

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW4#27]
In the linear_fit.py module, only uncertainties (sigma) in y have been accounted for, but not in x. Why do we not consider the x uncertainties?

**Comment by laserlab** [comment]
If you add appropriate milestone and mention the person for that task there is a higher chance for getting a response

**Comment by haiderabbas007** [comment]
@dnxjay

**Comment by dnxjay** [comment]
The x uncertainties are missing in both because the original pseudocode doesn’t include x uncertainties either. The pseudocode's calculations assume only y-uncertainties (sigma_i) affect the weighting

**Comment by iglesias-cardinale** [comment]
In principle one could add $\sigma_x$ but it would kind of drastically complicate the $\chi^2$ , no?

**Comment by haiderabbas007** [comment]
Yes it would complicate it. Moreover, we would have to make assumptions regarding $\sigma_x$ like the errors in x also following a Gaussian distribution. I think the pseudocode directs us to only consider $\sigma_y$ but yes in principal we could do the same for $\sigma_x$

**Comment by haiderabbas007** [comment]
Hope it makes sense...closing this now
