### ISSUE TITLE
9 group points or 8?

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW4#29]
The document says to 'Select the 9 groups (open circles) in Figure 1 of [Hubble's 1929 article](https://www.pnas.org/content/pnas/15/3/168.full.pdf) (due till Monday 2pm)(1 member). However, it appears that in both the original paper, and the reproduced plot, there are 8 points, not 9.

![image](https://github.com/user-attachments/assets/98d7267a-7e03-4433-964c-e08f4f3f9f08)

![image](https://github.com/user-attachments/assets/41b82532-5cf2-4f89-83ca-761c62e4b107)

Can someone please explain?

**Comment by Priyanka-43** [comment]
Yeah, I also noticed this thing. Is it possible to like there is overlap of black circle and open circle may be?

**Comment by haiderabbas007** [comment]
It might be, or it might just be a typo. Maybe it was indeed meant to be 8 points and was mistakenly written 9.

**Comment by Priyanka-43** [comment]
No, In paper as well, there is discussion about 9 groups not eight.

**Comment by haiderabbas007** [comment]
maybe it's dark matter which we can not see

**Comment by haiderabbas007** [comment]
@iglesias-cardinale

**Comment by iglesias-cardinale** [comment]
The nebulae are grouped like this

| Number in Naming Convention | Nebulae | Number of Nebulae |
| --------    | ------- | ------- |
| NA | S.Mag., L.Mag    |  2 |
| 0 - 1000 | 221, 224, 598    | 3 |
| 1000 - 2000     | 1068    | 1 |
| 2000 - 3000     | | 0 |
| 3000 - 4000     | 3031, 3627| 2 |
| 4000 - 5000     | 4258 , 4151, 4382, 4472 , 4486 , 4649 , 4449 , 4214 , 4826, 4736| 10 |
| 5000 - 6000     | 5236, 5055, 5457, 5194 | 4 |
| 6000 - 7000     | 6922| 1 |
| 7000 - 8000     | 7331| 1 |

So there are nine total groups, but one of them (2000 - 3000) doesn't have any data in it. Whether you count that one as a group is probably controversial, but Hubble apparently did.

**Comment by iglesias-cardinale** [comment]
> The nebulae are grouped like this
> 
> Number in Naming Convention	Nebulae	Number of Nebulae
> NA	S.Mag., L.Mag	2
> 0 - 1000	221, 224, 598	3
> 1000 - 2000	1068	1
> 2000 - 3000		0
> 3000 - 4000	3031, 3627	2
> 4000 - 5000	4258 , 4151, 4382, 4472 , 4486 , 4649 , 4449 , 4214 , 4826, 4736	10
> 5000 - 6000	5236, 5055, 5457, 5194	4
> 6000 - 7000	6922	1
> 7000 - 8000	7331	1
> So there are nine total groups, but one of them (2000 - 3000) doesn't have any data in it. Whether you count that one as a group is probably controversial, but Hubble apparently did.

I actually shouldn't say that Hubble counted this as a group. He didn't actually say in the paper what his grouping parameters were beyond "proximity in direction and in distance." So I'm actually just guessing that this is how he determined the groups. I just assume that this is how he formed the groups since it produces a similar plot, including the phantom ninth group point.

**Comment by haiderabbas007** [comment]
yeah, it's definitely a wimp
