### ISSUE TITLE
Team tools task

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW4#3]
Open discussion for the two maintainers to discuss how to implement the two tools.

**Comment by HeshamElsaman** [comment]
I guess I'll be joining you as a maintainer.
I can start looking into the pytesting framework for the code.
Is that okay?

**Comment by laserlab** [comment]
@kylemasc917 @HeshamElsaman Just gave you two maintainer rights

**Comment by laserlab** [comment]
Also what you might want to consider to make a PR template like the one @kylemasc917 suggested the last time.

**Comment by HeshamElsaman** [comment]
So, should we just add the workflows for linting and testing just as we had for the midterm and the last assignment?

**Comment by HeshamElsaman** [comment]
If so, @kylemasc917 would you work on the PR template and I'll try figuring out the linting and testing workflows?

**Comment by HeshamElsaman** [comment]
I've already committed the changes of adding the linting and testing workflows to my own branch. Please, let me know once you see this whether I should make a pull request for them for you to review it @kylemasc917 .

**Comment by HeshamElsaman** [comment]
Is it okay for the linting and testing workflows to be separated into two files, though?

**Comment by laserlab** [comment]
> Is it okay for the linting and testing workflows to be separated into two files, though?

That would make sense for this homework.

**Comment by kylemasc917** [comment]
Since we seem to have completed the tools task ill be closing this It can be reopened as needed.
