### ISSUE TITLE
'Selecting' the 9 groups

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW4#30]
The '9' groups were selected based on similar numerical values in the names of the nebulae. 'S. Mag' and 'L. Mag' do not have a numerical value associated with them. Why were they placed in the same group?

**Comment by laserlab** [comment]
If you add appropriate milestone and mention the person for that task there is a higher chance for getting a response

**Comment by haiderabbas007** [comment]
@iglesias-cardinale

**Comment by haiderabbas007** [comment]
> If you add appropriate milestone and mention the person for that task there is a higher chance for getting a response

Ok. Does 'Assignees' serve the same purpose as mentioning?

**Comment by iglesias-cardinale** [comment]
S. Mag and L. Mag are part of different Nebula clusters than all the others. The others are part of the NGC. 

S. Mag and L. mag also have similar velocities and distances, which is what the actual grouping criteria are. The numerical name value grouping is just a convenient side effect of grouping by proximity in position and velocity.

**Comment by haiderabbas007** [comment]
understood, thanks
