### ISSUE TITLE
Linting and Unit testing

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW4#33]
Is it necessary for our code to pass linting and unit testing before our PR can be approved?

**Comment by laserlab** [comment]
It’s up to the reviewer and maintainer to decide this

**Comment by haiderabbas007** [comment]
@HeshamElsaman 
@kylemasc917

**Comment by kylemasc917** [comment]
I would like it to be edited somewhat according to linting and testing standards but passing 100% is not required and the PR can be merged upon reviewer approval.

**Comment by zbpetersbuf** [comment]
Does our code need to pass flake8? or just somewhat to fully pass pylint? Cause I still dont know what exactly flake8 is, like its just another form of pylint but worse?

**Comment by avgagliardo** [comment]
> Does our code need to pass flake8? or just somewhat to fully pass pylint? Cause I still dont know what exactly flake8 is, like its just another form of pylint but worse?

flake8 is similar to pylint, its has the same ideas behind it but it uses a slightly different ruleset. Its a little more picky about some things and a little less picky about others compared to pylint. It also doesn't have a system that grades your code's linting score. 

For now, we are just worrying about using pylint so I wouldn't bring flake8 into the mix unless you are curious about the differences between the two.

**Comment by kylemasc917** [comment]
> Does our code need to pass flake8? or just somewhat to fully pass pylint? Cause I still dont know what exactly flake8 is, like its just another form of pylint but worse?

No It doesn't need to pass but try to edit it somewhat according to what the linting errors are saying like there shouldn't be any unnecessary whitespaces etc..

**Comment by haiderabbas007** [comment]
Thanks for your inputs
