### ISSUE TITLE
Clarification regarding pytest and lint with flake8

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW4#36]
I am doing  documentation part for the HW4. Yesterday, When i create pull request, there was pytest and  lint with flake error for documentation. Can i have more clarification on this?

**Comment by kylemasc917** [comment]
Its currently testing and linting every file in the repository so its ok that yours fails because some of the files already merged do not pass.

**Comment by Priyanka-43** [comment]
Ok. Thankyou so much for clarification.
