### ISSUE TITLE
im going to do the estimate the age of the universe bit

### ISSUE THREAD

**Issue by zbpetersbuf** [ubsuny/CP1-24-HW4#4]
I raised my hand for this part

**Comment by laserlab** [comment]
the coding part or the documentation one?

**Comment by laserlab** [comment]
@p-pxmpo got assigned the documentation and unit testing part

**Comment by zbpetersbuf** [comment]
the coding part was what i wanted to do, cool I forgot to respond to this message

**Comment by laserlab** [comment]
> the coding part was what i wanted to do, cool I forgot to respond to this message

perfect

**Comment by zbpetersbuf** [comment]
Hopefully I can start starting on Tuesday and do a bit more late Wednesday, my plan is if not already completed, to finish it on Thursday

**Comment by dnxjay** [comment]
Don't forget to close this issue when complete to earn points!

**Comment by zbpetersbuf** [comment]
im sorry I didn't close this when I was done
