### ISSUE TITLE
Reading back in from nonexistent file

### ISSUE THREAD

**Issue by jkblc** [ubsuny/CP1-24-HW4#41]
How do I write the code to read back the csv file data if there is no pull request with the csv file so that I correctly read the lines. Will my portion still be due on Friday at 2PM? I can open a pull request with some sample code.

**Comment by jkblc** [comment]
Or am I mistaken and the file [grouped_data_filtered.csv](https://github.com/ubsuny/CP1-24-HW4/blob/main/Least-squares%20Fit/grouped_data_filtered.csv) contain the distance and velocity as x and y

**Comment by haiderabbas007** [comment]
> Or am I mistaken and the file [grouped_data_filtered.csv](https://github.com/ubsuny/CP1-24-HW4/blob/main/Least-squares%20Fit/grouped_data_filtered.csv) contain the distance and velocity as x and y

yes [grouped_data_filtered.csv](https://github.com/ubsuny/CP1-24-HW4/blob/main/Least-squares%20Fit/grouped_data_filtered.csv) contains distance and velocity as x and y. I used x and y to match the requirements of the code in linear_fit.py which only extracts columns based on 'x' and 'y'

**Comment by jkblc** [comment]
Perfect, thanks
