### ISSUE TITLE
Using translated psuedocode versus using scipy.optimize

### ISSUE THREAD

**Issue by iglesias-cardinale** [ubsuny/CP1-24-HW4#47]
In PR #16 I used scipy.optimize to generate a fit of the data that looked similar to Hubble's original paper. I know the purpose of this homework is to build a fitting algorithm based on the provided psuedocode, so should I remove this file and do another pull request?

**Comment by haiderabbas007** [comment]
I'd say keep it but mention in the docstrings the difference

**Comment by dnxjay** [comment]
id say to keep it as well, not much of a need to add another PR

**Comment by iglesias-cardinale** [comment]
This makes sense. Thank you both.

**Comment by iglesias-cardinale** [comment]
Closing as resolved
