### ISSUE TITLE
Team Data and Documentation

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW4#6]
I will do the documentation part on how the 9 groups were selected.

**Comment by dhamalakamal** [comment]
I will be comparing the slope of the fitted straight line to Hubble's value of K.

**Comment by laserlab** [comment]
> I will be comparing the slope of the fitted straight line to Hubble's value of K.

Can you add that to s separate issue and assign the appropriate milestone?

**Comment by laserlab** [comment]
see issue #8

**Comment by Priyanka-43** [comment]
Hi, I didn't get that. Do I need to change my topic, because i have created this issue yesterday?

**Comment by laserlab** [comment]
It means work together with @iglesias-cardinale on this

**Comment by Priyanka-43** [comment]
Sure. Thankyou for clarification.
